DATA_PATH: "Data/VnStock_preprocessed.csv"

# PERIODS: { 
#             "sideway": ['2014-10-01','2016-03-01'],  #yyyy-mm-dd
#             "uptrend_1": ['2016-03-01','2018-03-01'],
#             "downtrend": ['2018-03-01','2020-03-01'],
#             "uptrend_2": ['2020-03-01','2021-12-31'],
#             "crisis_1": ['2018-10-04','2018-11-16'],
#             "crisis_2": ['2020-03-06','2020-04-01'],
#           }

PERIODS: {
          #"crisis_1": ['2018-01-31','2018-02-09'],
          #"crisis_2": ['2021-01-02','2021-01-19'],
          #"crisis_3": ['2018-10-04','2018-11-16'],
          #"crisis_4": ['2020-03-06','2020-04-01'],
          #"crisis_5": ['2018-12-12','2019-01-03'],
          #"downtrend_1": ['2018-02-09','2018-08-11'],
          #"downtrend_2": ['2014-08-29','2014-12-17'],
          #"downtrend_3": ['2015-02-24','2015-05-19'],
          #"downtrend_4": ['2014-03-21','2014-05-13'],
          #"downtrend_5": ['2020-01-22','2020-03-24'],
          "sideway_1": ['2019-02-21','2019-11-22'],
          #"sideway_2": ['2016-09-01','2017-01-01'],
          #"sideway_3": ['2017-02-09','2017-04-24'],
          #"sideway_4": ['2017-06-20','2017-08-28'],
          #"sideway_5": ['2015-08-28','2016-01-06'],
          #"uptrend_1": ['2013-09-01','2014-03-01'],
          #"uptrend_2": ['2014-05-12','2014-09-03'],
          #"uptrend_3": ['2017-09-03','2018-04-03'],
          #"uptrend_4": ['2020-07-24','2021-01-12'],
          #"uptrend_5": ['2021-01-26','2021-07-01'],
          }
 
BEGIN_DAY: '2009-12-22'

#SCENARIOS: ['sideway', 'uptrend_1', 'downtrend', 'uptrend_2', 'crisis_1'] #, 'crisis_2']

AGENTS: ['ddpg', 'ppo', 'td3', 'sac']

ERL_PARAMS: {"learning_rate": 0.0003 ,"batch_size": 2048, "gamma":  0.985,
            "seed": 312,"net_dimension": 512, "target_step": 100000, "eval_gap": 60,
            "eval_times": 1, 'learner_gpus': 7}

BREAK_STEP: 100000

RESULT_FOLDER: './results/Debug/'

TRAINED_MODEL_FOLDER: './trained_models/ElegantRL_smallperiod/'

TECHNICAL_INDICATORS_LIST: ['macd', 'boll_ub', 'boll_lb', 'rsi_30', 'cci_30', 'dx_30', 'close_30_sma', 'close_60_sma']