DATA_PATH: "Data/VN_stock_adjusted.csv"
#PERIODS: {"uptrend": ['2017-10-30','2018-04-03'], "downtrend": ['2018-12-03','2020-03-16'], "sideway" : ['2016-04-25','2017-07-17']}
PERIODS: { 
            #"sideway": ['2014-10-01','2016-03-01'],  #yyyy-mm-dd
            #"uptrend_1": ['2016-03-01','2018-03-01'],
            #"downtrend": ['2018-03-01','2020-03-01'],
            #"uptrend_2": ['2020-03-01','2021-12-31'],
            "crisis_1": ['2018-10-04','2018-11-16'],
            "crisis_2": ['2020-03-06','2020-04-01'],
          }

#PERIODS: {
          #"crisis_1": ['2018-01-31','2018-02-09'],
          #"crisis_2": ['2021-01-02','2021-01-19'],
          #"crisis_3": ['2018-10-04','2018-11-16'],
          #"crisis_4": ['2020-03-06','2020-04-01'],
          #"crisis_5": ['2018-12-12','2019-01-03'],
          #"downtrend_1": ['2018-02-09','2018-08-11'],
          #"downtrend_2": ['2014-08-29','2014-12-17'],
          #"downtrend_3": ['2015-02-24','2015-05-19'],
          #"downtrend_4": ['2014-03-21','2014-05-13'],
          #"downtrend_5": ['2020-01-22','2020-03-24'],
          #"sideway_1": ['2019-02-21','2019-11-22'],
          #"sideway_2": ['2016-09-01','2017-01-01'],
          #"sideway_3": ['2017-02-09','2017-04-24'],
          #"sideway_4": ['2017-06-20','2017-08-28'],
          #"sideway_5": ['2015-08-28','2016-01-06'],
          #"uptrend_1": ['2013-09-01','2014-03-01'],
          #"uptrend_2": ['2014-05-12','2014-09-03'],
          #"uptrend_3": ['2017-09-03','2018-04-03'],
          #"uptrend_4": ['2020-07-24','2021-01-12'],
          #"uptrend_5": ['2021-01-26','2021-07-01'],
          #}
 
BEGIN_DAY: '2009-12-22'
END_TRAIN: '2021-12-22'
#SCENARIOS: ['crisis_1', 'crisis_2'] #['sideway'] 
#SCENARIOS: ['sideway', 'uptrend_1', 'downtrend', 'uptrend_2', 'crisis_1', 'crisis_2']

#AGENTS: ['ddpg','sac','td3','a2c','ppo']
AGENTS: ['ddpg']


ERL_PARAMS: {"learning_rate": 0.0003 ,"batch_size": 4096, "gamma":  0.985,
            "seed": 312,"net_dimension": 512, "target_step": 100000, "eval_gap": 60,
            "eval_times": 1,"learner_gpus": -1, "if_use_per": False}

SB3_PARAMS: {"learning_rate": 0.003, "buffer_size": 1000000, "batch_size": 4096, "tau": 0.05, "gamma": 0.99,
            "tensorboard_log": True,"verbose": True, "device": 4, "seed": 312 }

BREAK_STEP : 100000

RESULT_FOLDER: './Results/Backtesting/'

TRAINED_MODEL_FOLDER: './TrainedModels/Backtesting/'

TECHNICAL_INDICATORS_LIST: ['macd', 'boll_ub', 'boll_lb', 'rsi_30', 'cci_30', 'dx_30', 'close_30_sma', 'close_60_sma']

VISUALIZE_TRADING_ACTION: True

BASELINE_PATH : "Data/VNIndex.csv"

PRICE_SCALER : 107.9 #Close price

MAX_STOCK : 30000

INITIAL_CAPITAL : 1000000

RLLIB : "ray"  # chose form stable_baselines, ray, elegantrl

WINDOW_SIZE : 60
