START_DAY: '2020-01-01'
END_DAY: '2021-12-31'

OBSERVATION_STEPS: 60
WAIT_STEPS: 30

DATA_PATH: "/mmlabworkspace/WorkSpaces/danhnt/tuyensh/khanhngo/AlgorithmicTrading/Data/VN_stock_adjusted.csv"

INIT_CASH: 1000000
LAMBDA: 1

SELL_ALL: True
#Sell all == True means that the algorithm will sell all the stocks at the end of 
#            period then buy according to the new portfolio proportion
#Sell all == False means that the algorithm will sell and buy to sastify the new portfolio proportion (minimize the trading cost)

SAVE_DIR: "Results"