START_DAY: '2020-03-01'
END_DAY: '2022-04-13'

OBSERVATION_STEPS: 240
WAIT_STEPS: 70

DATA_PATH: "/mmlabworkspace/WorkSpaces/danhnt/tuyensh/khanhngo/AlgorithmicTrading/Data/VN_stock_adjusted.csv"

INIT_CASH: 1000000
LAMBDA: 2

SELL_ALL: True
#Sell all == True means that the algorithm will sell all the stocks at the end of 
#            period then buy according to the new portfolio proportion
#Sell all == False means that the algorithm will sell and buy to sastify the new portfolio proportion (minimize the trading cost)

SAVE_DIR: "Results"